# Generated by Django 2.2.10 on 2020-02-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_verification_date',
            field=models.DateTimeField(null=True),
        ),
    ]
